### ISSUE TITLE
build fails for architecture os.linux.x86_64 on windows

### ISSUE THREAD

**Issue by gjr-qm** [bsliran/angular2-meteor-base#101]
Also mentioned in issue #76 

Running the application gives no errors, but when you try to build it with
`meteor build <outdir> --server-only --architecture os.linux.x86_64`  you get errors like:

File to read not found or unreadable: C:/test/angular-meteor-base/C:/test/angular-meteor-base/client/imports/app/todo-list/todo-list.scss

The process eventually finishes, but there's no styles in the tarball package.

It seems like the scss compiler doubles the paths on Windows...

**Comment by pedrolucasoliva** [comment]
I have the same issue here. Did you found some solution?
Seems like NODE-SASS problem.
Same problem eather on build at  "tabula rasa" repo clone:

`{ Error: File to read not found or unreadable: D:/Programação/angular-meteor-base/D:/Programação/angular-meteor-base/client/imports/app/todo-list/todo-list.scss
    at Object.module.exports.renderSync (C:\Users\pedro\AppData\Local\.meteor\packages\angular-compilers\0.2.8_1\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-scss-compiler\node_modules\node-sass\lib\index.js:439:16)
    at AngularScssCompiler.compileFile (packages/angular-scss-compiler/index.js:24:25)
    at TsCompilerAotCompilerTypeCheckHostAdapter.compiler._host.loadResource.filePath [as loadResource] (packages/angular-typescript-compiler/index.js:279:45)
    at Object.get (C:\Users\pedro\AppData\Local\.meteor\packages\angular-compilers\0.2.8_1\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\aot\compiler_factory.js:78:306)
    at DirectiveNormalizer._fetch (C:\Users\pedro\AppData\Local\.meteor\packages\angular-compilers\0.2.8_1\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\directive_normalizer.js:95:7)
    at C:\Users\pedro\AppData\Local\.meteor\packages\angular-compilers\0.2.8_1\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\directive_normalizer.js:292:36
    at Array.map (<anonymous>)
    at DirectiveNormalizer._loadMissingExternalStylesheets (C:\Users\pedro\AppData\Local\.meteor\packages\angular-compilers\0.2.8_1\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\directive_normalizer.js:291:14)
    at DirectiveNormalizer._normalizeTemplateMetadata (C:\Users\pedro\AppData\Local\.meteor\packages\angular-compilers\0.2.8_1\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\directive_normalizer.js:201:7)
    at C:\Users\pedro\AppData\Local\.meteor\packages\angular-compilers\0.2.8_1\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\directive_normalizer.js:127:7
    at Object.then (C:\Users\pedro\AppData\Local\.meteor\packages\angular-compilers\0.2.8_1\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\util.js:164:3)
    at DirectiveNormalizer.normalizeTemplate (C:\Users\pedro\AppData\Local\.meteor\packages\angular-compilers\0.2.8_1\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\directive_normalizer.js:127:7)
    at CompileMetadataResolver.loadDirectiveMetadata (C:\Users\pedro\AppData\Local\.meteor\packages\angular-compilers\0.2.8_1\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\metadata_resolver.js:361:44)
    at C:\Users\pedro\AppData\Local\.meteor\packages\angular-compilers\0.2.8_1\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\metadata_resolver.js:614:54
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.loadNgModuleDirectiveAndPipeMetadata (C:\Users\pedro\AppData\Local\.meteor\packages\angular-compilers\0.2.8_1\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\metadata_resolver.js:613:16)
    at C:\Users\pedro\AppData\Local\.meteor\packages\angular-compilers\0.2.8_1\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\aot\compiler.js:91:7
    at Array.map (<anonymous>)
    at AotCompiler.analyzeModulesAsync (C:\Users\pedro\AppData\Local\.meteor\packages\angular-compilers\0.2.8_1\plugin.Angular_Compilers.os\npm\node_modules\meteor\angular-typescript-compiler\node_modules\packages\compiler\esm5\src\aot\compiler.js:91:7)
    at Promise.asyncApply (packages/angular-typescript-compiler/index.js:297:42)
    at C:\Users\pedro\AppData\Local\.meteor\packages\meteor-tool\1.6.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\fiber_pool.js:43:40
  status: 3,
  message: 'File to read not found or unreadable: D:/Programação/angular-meteor-base/D:/Programação/angular-meteor-base/client/imports/app/todo-list/todo-list.scss',
  formatted: 'Internal Error: File to read not found or unreadable: D:/Programação/angular-meteor-base/D:/Programação/angular-meteor-base/client/imports/app/todo-list/todo-list.scss\n' }`

**Comment by gjr-qm** [comment]
No solution for me yet. I attempted to fix it in the source code, but I didn't have enough time for that.

At the moment I do my builds/deployments from a Linux container. Would be very nice if this bug gets fixed. I think it can't be much work for someone with knowledge of the source code.

Maybe later I can try to fix this myself if I have some more time. Is there some info out there that could be helpful for understanding the architecture of the compiler modules?

**Comment by pedrofg** [comment]
Same error here.

**Comment by fidelsam1992** [comment]
It was solved with me upgrading the versions of those packages : 
in the versions file
angular-compilers@0.2.9_2
angular-html-compiler@0.2.9
angular-scss-compiler@0.2.9
angular-typescript-compiler@0.2.9_5

**Comment by ardatan** [comment]
Thank you for contributing!
Boilerplate has been updated, if you have still the same error please feel free to open a new issue.
