### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by metalik** [bsliran/angular2-meteor-base#42]
Below is the build error logs:

```
Errors prevented bundling:
While processing files with angular2-compilers (for target web.browser):
C:\tools\isobuild\compiler-plugin.js:698:15: 'data' option to addAsset
must be a Buffer or String.
at ResourceSlot.addAsset (C:\tools\isobuild\compiler-plugin.js:698:15)
at InputFile.addAsset (C:\tools\isobuild\compiler-plugin.js:463:24)
at SassCompilerExtended.addCompileResult
(packages/barbatus:css-compiler/compilers/basic_compiler.js:32:15)
at packages/caching-compiler/multi-file-caching-compiler.js:144:14
at packages/caching-compiler/multi-file-caching-compiler.js:97:11
at C:\Users\XXX\AppData\Local\.meteor\packages\angular2-compilers\0.6.3\plugin.Angular2Compilers.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:182:20
at replenish (C:\Users\XXX\AppData\Local\.meteor\packages\angular2-compilers\0.6.3\plugin.Angular2Compilers.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:317:21)
at C:\Users\XXX\AppData\Local\.meteor\packages\angular2-compilers\0.6.3\plugin.Angular2Compilers.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:328:15
at Object.async.forEachLimit.async.eachLimit (C:\Users\XXX\AppData\Local\.meteor\packages\angular2-compilers\0.6.3\plugin.Angular2Compilers.os\npm\node_modules\meteor\caching-compiler\node_modules\async\lib\async.js:221:35)
at SassCompilerExtended.processFilesForTarget
(packages/caching-compiler/multi-file-caching-compiler.js:95:11)
at _loop
(packages/barbatus:css-compiler/compilers/style_compiler.js:20:26)
at StyleCompiler.processFilesForTarget
(packages/barbatus:css-compiler/compilers/style_compiler.js:18:36)
```

**Comment by metalik** [comment]
The issue should be related to angular2-meteor.

#https://github.com/Urigo/angular2-meteor/issues/427
