### ISSUE TITLE
Quick start broken?

### ISSUE THREAD

**Issue by jkdowdle** [bsliran/angular2-meteor-base#44]
I am having trouble getting this git repository to work. 

I first ran `git clone https://github.com/bsliran/angular2-meteor-base test3`

Then `meteor`

Then it gives me this error  

```
=> Started proxy.
=> Started MongoDB.
client/imports/app/demo/demo-data.service.ts (1, 28): Cannot find module '@angular/core'.
client/imports/app/demo/demo-data.service.ts (2, 34): Cannot find module 'meteor-rxjs'.
client/imports/app/demo/demo.component.ts (1, 35): Cannot find module '@angular/core'.
client/imports/app/demo/demo.component.ts (2, 28): Cannot find module 'rxjs/Observable'.
client/imports/app/app.component.ts (1, 27): Cannot find module '@angular/core'.
client/imports/app/app.module.ts (1, 26): Cannot find module '@angular/core'.
client/imports/app/app.module.ts (2, 31): Cannot find module '@angular/platform-browser'.
both/collections/demo.collection.ts (1, 33): Cannot find module 'meteor-rxjs'.
client/main.ts (3, 40): Cannot find module '@angular/platform-browser-dynamic'.
client/main.ts (4, 32): Cannot find module '@angular/core'.
client/main.ts (5, 24): Cannot find module 'meteor/meteor'.

Unable to resolve some modules:

  "meteor-rxjs" in /C/Users/Joshua Dowdle/angularMeteor/test3/both/collections/demo.collection.js (web.browser)
  "angular2-meteor-polyfills" in /C/Users/Joshua Dowdle/angularMeteor/test3/client/main.js (web.browser)
  "@angular/platform-browser-dynamic" in /C/Users/Joshua Dowdle/angularMeteor/test3/client/main.js (web.browser)
  "@angular/core" in /C/Users/Joshua Dowdle/angularMeteor/test3/client/imports/app/demo/demo-data.service.js (web.browser)
  "@angular/platform-browser" in /C/Users/Joshua Dowdle/angularMeteor/test3/client/imports/app/app.module.js (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save meteor-rxjs angular2-meteor-polyfills @angular


Unable to resolve some modules:

  "meteor-rxjs" in /C/Users/Joshua Dowdle/angularMeteor/test3/both/collections/demo.collection.js (os.windows.x86_32)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save meteor-rxjs

W20161026-19:30:15.405(-6)? (STDERR) C:\Users\Joshua Dowdle\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20161026-19:30:16.058(-6)? (STDERR)                                            throw(ex);
W20161026-19:30:16.059(-6)? (STDERR)                                            ^
W20161026-19:30:16.060(-6)? (STDERR)
W20161026-19:30:16.060(-6)? (STDERR) Error: Can't find npm module 'meteor-rxjs'. Did you forget to call 'Npm.depends' in package.js within the 'modules-runtime' package?
W20161026-19:30:16.061(-6)? (STDERR)     at Object.require (C:\Users\Joshua Dowdle\angularMeteor\test3\.meteor\local\build\programs\server\boot.js:200:17)
W20161026-19:30:16.062(-6)? (STDERR)     at options.fallback (packages\modules-runtime.js:445:18)
W20161026-19:30:16.063(-6)? (STDERR)     at require (packages\modules-runtime.js:112:16)
W20161026-19:30:16.064(-6)? (STDERR)     at meteorInstall.both.collections.demo.collection.js (both/collections/demo.collection.ts:1:1)
W20161026-19:30:16.065(-6)? (STDERR)     at fileEvaluate (packages\modules-runtime.js:181:9)
W20161026-19:30:16.069(-6)? (STDERR)     at require (packages\modules-runtime.js:106:16)
W20161026-19:30:16.070(-6)? (STDERR)     at server/main.ts:4:22
W20161026-19:30:16.070(-6)? (STDERR)     at C:\Users\Joshua Dowdle\angularMeteor\test3\.meteor\local\build\programs\server\boot.js:295:34
W20161026-19:30:16.071(-6)? (STDERR)     at Array.forEach (native)
W20161026-19:30:16.072(-6)? (STDERR)     at Function._.each._.forEach (C:\Users\Joshua Dowdle\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
=> Exited with code: 1
client/imports/app/demo/demo-data.service.ts (1, 28): Cannot find module '@angular/core'.
client/imports/app/demo/demo-data.service.ts (2, 34): Cannot find module 'meteor-rxjs'.
client/imports/app/demo/demo.component.ts (1, 35): Cannot find module '@angular/core'.
client/imports/app/demo/demo.component.ts (2, 28): Cannot find module 'rxjs/Observable'.
client/imports/app/app.component.ts (1, 27): Cannot find module '@angular/core'.
client/imports/app/app.module.ts (1, 26): Cannot find module '@angular/core'.
client/imports/app/app.module.ts (2, 31): Cannot find module '@angular/platform-browser'.
both/collections/demo.collection.ts (1, 33): Cannot find module 'meteor-rxjs'.
client/main.ts (3, 40): Cannot find module '@angular/platform-browser-dynamic'.
client/main.ts (4, 32): Cannot find module '@angular/core'.
client/main.ts (5, 24): Cannot find module 'meteor/meteor'.
```

When I run the commands it suggests it dose not solve anything.

Any help would be appreciated, thank you.

**Comment by nebiljabari** [comment]
Sound like a classic missing npm packages

Have you opted for this procedure ? :

```
1 - meteor create --example angular2-boilerplate test3
2 - cd test3
3 - meteor npm i
```

if it don't succeed try for n°3 : `npm i`

**Comment by jkdowdle** [comment]
@nebiljabari 

Thank you so much for responding. I do appreciate it. ok so I am a little confused, when I run 

`meteor create --example angular2-boilerplate test5`

Should it just create a project downloading the git repo? 

When I run that command I get the following message

```
To create the angular2-boilerplate example, please run:
  git clone https://github.com/bsliran/angular2-meteor-base test5
```

Does it matter than I am using Windows 10?
NPM version - 3.10.7 
git version 2.10.0.windows.1
Meteor 1.4.2

**Comment by jkdowdle** [comment]
@nebiljabari 

I tried your second solution running npm i and it started the app with out problems. Thank you very much, it is a huge relief. I am still wondering why the first solution didn't work and would love to know, but again thanks a ton.

**Comment by nebiljabari** [comment]
With pleasure @jkdowdle, I think here we all know what it feel to be alone with an error ;-)

Im on Mac so I don't know precisely "why" it happened on Windows. 
But if you want to know about the difference between `meteor npm i`and `npm i` some info : [here](https://forums.meteor.com/t/what-if-i-dont-put-meteor-in-front-of-npm-install/30680/5)

I think we can close this issue

**Comment by jkdowdle** [comment]
Ok great I will check that out! 

Thank you!
